import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the infoProduct slice
const initialPopUPState = { infoProduct: {} };

const infoProductSlice = createSlice({
    name: "inforProduct",
    initialState: initialPopUPState,
    reducers: {
        // Reducer function to set the infoProduct state
        setInfoProduct(state, action) {
            // Remove existing product detail from local storage
            localStorage.removeItem("productDetail");

            // Update the infoProduct state with the new payload
            state.infoProduct = action.payload;
        },
    },
});

// Export the action creators generated by the infoProductSlice
export const infoProductActions = infoProductSlice.actions;

export default infoProductSlice.reducer;
