import { createSlice } from "@reduxjs/toolkit";

import { saveToStorage, getFromStorage } from "../utils";

// get product detail from local storage, or initialize as an empty object
const productDetail = JSON.parse(getFromStorage("productDetail")) || {};

// Define the initial state for the infoProduct slice
const initialPopUPState = { infoProduct: productDetail };

const infoProductSlice = createSlice({
    name: "inforProduct",
    initialState: initialPopUPState,
    reducers: {
        // Reducer function to set the infoProduct state
        setInfoProduct(state, action) {
            // Remove existing product detail from local storage
            localStorage.removeItem("productDetail");

            // Update the infoProduct state with the new payload
            state.infoProduct = action.payload;

            // Save the updated product detail to local storage
            saveToStorage("productDetail", JSON.stringify(state.infoProduct));
        },
    },
});

// Export the action creators generated by the infoProductSlice
export const infoProductActions = infoProductSlice.actions;

export default infoProductSlice.reducer;
