import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the message slice
const initialMessageUPState = { isShow: false };

const messageSlice = createSlice({
    name: "message",
    initialState: initialMessageUPState,
    reducers: {
        // Reducer function to toggle the isShow state
        toggleShowMessageUp(state) {
            state.isShow = !state.isShow;
        },
    },
});

// Export the action creators generated by the messageSlice
export const messageActions = messageSlice.actions;

export default messageSlice.reducer;
