import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the pop slice
const initialPopUPState = { infoProduct: {}, isShow: false };

const popSlice = createSlice({
    name: "popup",
    initialState: initialPopUPState,
    reducers: {
        // Reducer function to show the pop-up and update the infoProduct
        showPopUp(state, action) {
            state.isShow = true;
            state.infoProduct = action.payload;
        },

        // Reducer function to hide the pop-up
        hidePopUp(state) {
            state.isShow = false;
        },
    },
});

// Export the action creators generated by the popSlice
export const popActions = popSlice.actions;

export default popSlice.reducer;
